export default {
  "login": "meta",
  "id": 5732757,
  "node_id": "MDQ6VXNlcjU3MzI3NTc=",
  "avatar_url": "https://avatars.githubusercontent.com/u/5732757?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/meta",
  "html_url": "https://github.com/meta",
  "followers_url": "https://api.github.com/users/meta/followers",
  "following_url": "https://api.github.com/users/meta/following{/other_user}",
  "gists_url": "https://api.github.com/users/meta/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/meta/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/meta/subscriptions",
  "organizations_url": "https://api.github.com/users/meta/orgs",
  "repos_url": "https://api.github.com/users/meta/repos",
  "events_url": "https://api.github.com/users/meta/events{/privacy}",
  "received_events_url": "https://api.github.com/users/meta/received_events",
  "type": "User",
  "site_admin": false,
  "name": "T on Meta Mode",
  "company": null,
  "blog": "",
  "location": "United States",
  "email": null,
  "hireable": null,
  "bio": "Prev. Spec: (AWS, Web, DevOps, Infra, DL)\r\n--\r\nCurrent Spec: Distributed ML Training",
  "twitter_username": null,
  "public_repos": 11,
  "public_gists": 0,
  "followers": 54,
  "following": 2,
  "created_at": "2013-10-20T21:39:32Z",
  "updated_at": "2024-01-06T20:24:18Z"
}